services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
      
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data

  mongoexpress:
    image: mongo-express
    environment: 
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopw
    ports:
      - 8081:8081
    depends_on:
      - mongodb
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
        
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "Mtbs2023*"
    ports:
        - "1433:1433"
