# networks:
#   custom:
#     ipam:
#       config:
#         - subnet: 10.5.0.0/16

services:      
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
    # networks:
    #   custom:

  mongoexpress:
    image: mongo-express
    environment: 
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopw
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    # networks:
    #   custom:
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    # networks:
    #   custom:
        
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "Mtbs2023*"
    ports:
        - "1533:1433"
    # networks:
    #   custom:

  auction-svc:
    image: auction-svc:latest
    build: 
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=mssql;User Id=sa;Password=Mtbs2023*;Database=auctions;TrustServerCertificate=True
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - mssql
      - rabbitmq
    # networks:
    #   custom:

  search-svc:
    image: search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
    # networks:
    #   custom:

  identity-svc:
    image: identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      # - ClientApp=http://app.carsties.com
      - ConnectionStrings__DefaultConnection=Server=mssql;User Id=sa;Password=Mtbs2023*;Database=identity;TrustServerCertificate=True
      # - VIRTUAL_HOST=id.carsties.com
    ports:
      - 5000:80
    depends_on:
      - mssql
    # networks:
    #   custom:
    #     ipv4_address: 10.5.0.200

  gateway-svc:
    image: gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
  #     - ClientApp=https://app.carsties.com
  #     - VIRTUAL_HOST=api.carsties.com
  #   networks:
  #     custom: